-- ISS124 regression — run on disposable only.
-- Requires the six owner UCL fixtures to have been regenerated by the real builder
-- at decision_time 2026-09-10 12:00:00+00.

-- A. All six crossleague_v1_1 fixtures must expose one active, temporal MODEL row
-- linked to their frozen feature snapshot.
DO $$
DECLARE n int;
BEGIN
  with ids(event_id) as (
    values ('401915422'),('401915440'),('401915441'),
           ('401915442'),('401915443'),('401915444')
  ), q as (
    select i.event_id,
           bool_or(d.source_name='modelo_p_reto'
                   and d.available
                   and d.used_in_p_reto
                   and d.temporally_safe
                   and d.feature_snapshot_id is not null
                   and d.feature_version='domestic_form_phi_v1_1'
                   and d.provenance like '%model_version=crossleague_v1_1%') ok
    from ids i
    cross join lateral v2.fn_soccer_dossier_manifest(
      i.event_id,'2026-09-10 12:00:00+00'::timestamptz) d
    group by i.event_id
  )
  select count(*) into n from q where ok;
  if n <> 6 then
    raise exception 'ISS124_FAIL: expected dossier green 6/6, got %/6', n;
  end if;
END $$;

-- B. Adversarial: a second staged brain for the same event+decision must not be chosen.
BEGIN;
insert into v2.soccer_prediction_v2_staged
select s.espn_event_id,s.competition_id,s.home_team,s.away_team,s.kickoff,s.decision_time,
       s.feature_data_asof,s.max_source_event_time,s.sample_home,s.sample_away,s.temporal_safe,
       s.feature_version,'audit_conflicting_brain',s.calibration_status,
       s.p_home,s.p_draw,s.p_away,s.btts_yes,s.btts_no,s.over_line,s.p_over,s.p_under,
       s.line_source,s.line_asof,s.model_status,s.model_status_reason,s.provenance,
       s.competition_mapping_version,s.availability_verified,s.score_dist,s.top_scores,
       s.p_push,s.ou_line_type,s.ou_supported,s.feature_snapshot_id,now(),s.model_name,s.model_route
from v2.soccer_prediction_v2_staged s
where s.espn_event_id='401915422'
  and s.decision_time='2026-09-10 12:00:00+00'::timestamptz
  and s.model_version='crossleague_v1_1';

DO $$
DECLARE r record;
BEGIN
  select * into r
  from v2.fn_soccer_dossier_manifest('401915422','2026-09-10 12:00:00+00'::timestamptz)
  limit 1;
  if r.freshness_status is distinct from 'AMBIGUOUS_CANONICAL_STAGED'
     or coalesce(r.available,true)
     or coalesce(r.used_in_p_reto,true) then
    raise exception 'ISS124_FAIL: ambiguity did not fail closed';
  end if;
END $$;
ROLLBACK;
