-- ISS138 — Soccer secondary markets: official selective O/U 1.5 + shadow BTTS/totals
-- 2026-09-14
-- Scientific contract:
-- * O/U 1.5 model parameters selected using data strictly before 2025-08-01.
-- * Publication threshold >=75% selected in Aug-Nov 2025 validation.
-- * Independent Dec-Feb 2026 confirmation: n=328, win=79.57%, avg confidence=79.84%,
--   Brier 0.160224 vs baseline 0.164436, paired upper95=-0.000058.
-- * Closing market remains better (Brier 0.156340): money/EV/Kelly remain CLOSED.
-- * BTTS and O/U 2.5/3.5/4.5 remain CHALLENGER/SHADOW; no official probability/pick.
-- * Market/no-vig never enters P_RETO.

create table if not exists v2.soccer_secondary_model_registry_v1 (
  model_version text primary key,
  market_key text not null,
  line numeric,
  validation_status text not null,
  scientific_ready boolean not null default false,
  publish_authorized boolean not null default false,
  money_authorized boolean not null default false,
  release_threshold_pct numeric,
  training_cutoff timestamptz,
  validation_evidence jsonb not null default '{}'::jsonb,
  sealed_at timestamptz not null default now(),
  check (not money_authorized or publish_authorized),
  check (release_threshold_pct is null or release_threshold_pct between 50 and 100)
);

create table if not exists v2.soccer_secondary_market_policy_v1 (
  endpoint text not null,
  model_version text not null references v2.soccer_secondary_model_registry_v1(model_version),
  publish_authorized boolean not null default false,
  reason text,
  updated_at timestamptz not null default now(),
  primary key(endpoint,model_version)
);

create table if not exists v2.soccer_secondary_prediction_v1 (
  id bigint generated by default as identity primary key,
  espn_event_id text not null,
  endpoint text not null,
  home_team text not null,
  away_team text not null,
  kickoff timestamptz not null,
  decision_time timestamptz not null,
  data_asof timestamptz,
  market_key text not null,
  market_label text not null,
  line numeric,
  p_yes numeric,
  p_no numeric,
  candidate_pick text,
  candidate_pick_prob numeric,
  model_version text not null,
  model_status text not null,
  temporal_safe boolean not null,
  feature_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(espn_event_id,market_key,model_version,decision_time),
  check (p_yes is null or p_yes between 0 and 100),
  check (p_no is null or p_no between 0 and 100),
  check (candidate_pick_prob is null or candidate_pick_prob between 0 and 100)
);
create index if not exists soccer_secondary_prediction_event_idx
  on v2.soccer_secondary_prediction_v1(espn_event_id,market_key,decision_time desc);
create index if not exists soccer_secondary_prediction_kickoff_idx
  on v2.soccer_secondary_prediction_v1(kickoff,model_version);

insert into v2.soccer_secondary_model_registry_v1
(model_version,market_key,line,validation_status,scientific_ready,publish_authorized,money_authorized,release_threshold_pct,training_cutoff,validation_evidence,sealed_at)
values
('soccer_total15_v1','TOTAL_1_5',1.5,'OOS_TEMPORAL_VALIDATED_SELECTIVE',true,true,false,75,'2025-08-01T00:00:00Z',
 jsonb_build_object(
   'feature_contract','540d prior-only goals + exact live xG_est formula; weight_xg=0.25; shrink_k=30; Poisson total',
   'parameter_selection','strictly pre-2025-08-01',
   'validation_aug_nov_2025',jsonb_build_object('n',384,'win_pct',79.69,'avg_conf_pct',79.82,'brier',0.162144,'threshold_pct',75),
   'confirmation_dec_feb_2026',jsonb_build_object('n',328,'win_pct',79.57,'avg_conf_pct',79.84,'brier_model',0.160224,'brier_baseline',0.164436,'paired_upper95',-0.000058,'brier_market_close',0.156340),
   'money_gate','CLOSED_MARKET_REFERENCE_BETTER'),now()),
('soccer_btts_occurrence_v1_challenger','BTTS',null,'CHALLENGER_CONFIRMATION_FAIL',false,false,false,60,'2025-08-01T00:00:00Z',
 jsonb_build_object('validation_aug_nov_2025',jsonb_build_object('n',82,'win_pct',63.41,'brier_model',0.233062,'brier_baseline',0.235611),
                    'confirmation_dec_feb_2026',jsonb_build_object('n',56,'win_pct',57.14,'brier_model',0.249052,'brier_baseline',0.242617,'paired_upper95',0.018749),
                    'decision','SHADOW_ONLY'),now()),
('soccer_total25_v1_challenger','TOTAL_2_5',2.5,'CHALLENGER_EARLY_SEASON_NOT_PROVEN',false,false,false,62.5,'2025-08-01T00:00:00Z',
 jsonb_build_object('validation_aug_nov_2025',jsonb_build_object('n',107,'win_pct',65.42,'avg_conf_pct',65.88),
                    'confirmation_dec_feb_2026',jsonb_build_object('n',88,'win_pct',64.77,'paired_upper95',0.011789),'decision','SHADOW_ONLY'),now()),
('soccer_total35_v1_challenger','TOTAL_3_5',3.5,'CHALLENGER_CONFIRMATION_BORDERLINE',false,false,false,72.5,'2025-08-01T00:00:00Z',
 jsonb_build_object('validation_aug_nov_2025',jsonb_build_object('n',193,'win_pct',78.24,'avg_conf_pct',77.53),
                    'confirmation_dec_feb_2026',jsonb_build_object('n',236,'win_pct',75.85,'paired_upper95',0.000414),'decision','SHADOW_ONLY'),now()),
('soccer_total45_v1_challenger','TOTAL_4_5',4.5,'CHALLENGER_CONFIRMATION_BORDERLINE',false,false,false,80,'2025-08-01T00:00:00Z',
 jsonb_build_object('validation_aug_nov_2025',jsonb_build_object('n',470,'win_pct',89.15,'avg_conf_pct',86.18),
                    'confirmation_dec_feb_2026',jsonb_build_object('n',489,'win_pct',88.14,'paired_upper95',0.001426),'decision','SHADOW_ONLY'),now())
on conflict(model_version) do update set
  market_key=excluded.market_key,line=excluded.line,validation_status=excluded.validation_status,
  scientific_ready=excluded.scientific_ready,publish_authorized=excluded.publish_authorized,
  money_authorized=excluded.money_authorized,release_threshold_pct=excluded.release_threshold_pct,
  training_cutoff=excluded.training_cutoff,validation_evidence=excluded.validation_evidence,sealed_at=excluded.sealed_at;

insert into v2.soccer_secondary_market_policy_v1(endpoint,model_version,publish_authorized,reason)
select e.endpoint,r.model_version,(r.model_version='soccer_total15_v1') as publish_authorized,
       case when r.model_version='soccer_total15_v1' then 'Top-5 league exact feature contract; selective O/U 1.5 OOS-confirmed.'
            else 'Shadow challenger only; no product publication.' end
from (values ('soccer/eng.1'),('soccer/esp.1'),('soccer/ger.1'),('soccer/fra.1'),('soccer/ita.1')) e(endpoint)
cross join v2.soccer_secondary_model_registry_v1 r
where r.model_version in ('soccer_total15_v1','soccer_btts_occurrence_v1_challenger','soccer_total25_v1_challenger','soccer_total35_v1_challenger','soccer_total45_v1_challenger')
on conflict(endpoint,model_version) do update set publish_authorized=excluded.publish_authorized,reason=excluded.reason,updated_at=now();

create or replace function v2.fn_soccer_secondary_market_v1(p_event_id text,p_decision_time timestamptz default now())
returns table(
  espn_event_id text,endpoint text,home_team text,away_team text,kickoff timestamptz,decision_time timestamptz,data_asof timestamptz,
  market_key text,market_label text,line numeric,p_yes numeric,p_no numeric,candidate_pick text,candidate_pick_prob numeric,
  model_version text,model_status text,temporal_safe boolean,feature_snapshot jsonb
)
language sql stable security definer
set search_path='v2','public','pg_temp'
as $$
with fx as (
  select a.espn_event_id,a.espn_endpoint endpoint,a.home_espn_id,a.away_espn_id,a.home_nombre,a.away_nombre,a.fecha kickoff
  from public.agenda_espn a
  where a.espn_event_id=p_event_id and a.deporte='soccer'
    and a.espn_endpoint in ('soccer/eng.1','soccer/esp.1','soccer/ger.1','soccer/fra.1','soccer/ita.1')
  limit 1
), hist as (
  select v.*,
    (select max(d.cargado_at) from public.detalle_partido_espn d
      where d.espn_event_id=v.espn_event_id and d.cargado_at<=p_decision_time) loaded_at
  from public.v_equipo_partido_espn_xg v cross join fx
  where v.endpoint=fx.endpoint and v.fecha<fx.kickoff and v.fecha>=fx.kickoff-interval '540 days'
    and exists(select 1 from public.detalle_partido_espn d where d.espn_event_id=v.espn_event_id and d.cargado_at<=p_decision_time)
), hh as (
  select count(*)::int n,sum(gf)::numeric sgf,sum(gc)::numeric sga,sum(xg_est_favor)::numeric sxgf,sum(xg_est_contra)::numeric sxga,
    count(*) filter(where es_local)::int n_home,
    count(*) filter(where es_local and gf>0)::numeric scored_home,
    count(*) filter(where es_local and gc>0)::numeric conceded_home,
    count(*) filter(where gf>0)::numeric scored_all,count(*) filter(where gc>0)::numeric conceded_all,
    max(loaded_at) data_asof
  from hist cross join fx where equipo=fx.home_espn_id
), aa as (
  select count(*)::int n,sum(gf)::numeric sgf,sum(gc)::numeric sga,sum(xg_est_favor)::numeric sxgf,sum(xg_est_contra)::numeric sxga,
    count(*) filter(where not es_local)::int n_away,
    count(*) filter(where not es_local and gf>0)::numeric scored_away,
    count(*) filter(where not es_local and gc>0)::numeric conceded_away,
    count(*) filter(where gf>0)::numeric scored_all,count(*) filter(where gc>0)::numeric conceded_all,
    max(loaded_at) data_asof
  from hist cross join fx where equipo=fx.away_espn_id
), lg as (
  select
    avg(gf::numeric) filter(where es_local) lhg,avg(gf::numeric) filter(where not es_local) lag,
    avg(xg_est_favor) filter(where es_local) lhx,avg(xg_est_favor) filter(where not es_local) lax,
    avg((gf>0)::int::numeric) filter(where es_local) phs,
    avg((gf>0)::int::numeric) filter(where not es_local) pas,
    max(loaded_at) data_asof
  from hist
), z as (
 select fx.*,hh.n hn,aa.n an,hh.data_asof h_asof,aa.data_asof a_asof,lg.data_asof lg_asof,
   hh.sgf hgf,hh.sga hga,hh.sxgf hxgf,hh.sxga hxga,aa.sgf agf,aa.sga aga,aa.sxgf axgf,aa.sxga axga,
   hh.n_home,hh.scored_home,hh.conceded_home,hh.scored_all h_scored_all,hh.conceded_all h_conceded_all,
   aa.n_away,aa.scored_away,aa.conceded_away,aa.scored_all a_scored_all,aa.conceded_all a_conceded_all,
   lg.lhg,lg.lag,lg.lhx,lg.lax,lg.phs,lg.pas
 from fx cross join hh cross join aa cross join lg
), calc as (
 select z.*,
   -- O/U 1.5: fixed pre-validation parameters weight_xG=.25, shrink=30
   greatest(.05,(((((.75*hgf+.25*hxgf)+30*(.75*lhg+.25*lhx))/(hn+30))*(((.75*aga+.25*axga)+30*(.75*lhg+.25*lhx))/(an+30)))/nullif((.75*lhg+.25*lhx),0)) l15h,
   greatest(.05,(((((.75*agf+.25*axgf)+30*(.75*lag+.25*lax))/(an+30))*(((.75*hga+.25*hxga)+30*(.75*lag+.25*lax))/(hn+30)))/nullif((.75*lag+.25*lax),0)) l15a,
   -- O/U 2.5/3.5 shadow: weight_xG=.25, shrink=12
   greatest(.05,(((((.75*hgf+.25*hxgf)+12*(.75*lhg+.25*lhx))/(hn+12))*(((.75*aga+.25*axga)+12*(.75*lhg+.25*lhx))/(an+12)))/nullif((.75*lhg+.25*lhx),0)) l25h,
   greatest(.05,(((((.75*agf+.25*axgf)+12*(.75*lag+.25*lax))/(an+12))*(((.75*hga+.25*hxga)+12*(.75*lag+.25*lax))/(hn+12)))/nullif((.75*lag+.25*lax),0)) l25a,
   -- O/U 4.5 shadow: weight_xG=.50, shrink=8
   greatest(.05,(((((.5*hgf+.5*hxgf)+8*(.5*lhg+.5*lhx))/(hn+8))*(((.5*aga+.5*axga)+8*(.5*lhg+.5*lhx))/(an+8)))/nullif((.5*lhg+.5*lhx),0)) l45h,
   greatest(.05,(((((.5*agf+.5*axgf)+8*(.5*lag+.5*lax))/(an+8))*(((.5*hga+.5*hxga)+8*(.5*lag+.5*lax))/(hn+8)))/nullif((.5*lag+.5*lax),0)) l45a,
   -- BTTS occurrence challenger: occurrence rates + Poisson/xG blend selected pre-validation.
   .5*((h_scored_all+4*phs)/(hn+4))+.5*((coalesce(scored_home,0)+4*phs)/(coalesce(n_home,0)+4)) hscore,
   .5*((a_conceded_all+4*phs)/(an+4))+.5*((coalesce(conceded_away,0)+4*phs)/(coalesce(n_away,0)+4)) aconcede,
   .5*((a_scored_all+4*pas)/(an+4))+.5*((coalesce(scored_away,0)+4*pas)/(coalesce(n_away,0)+4)) ascore,
   .5*((h_conceded_all+4*pas)/(hn+4))+.5*((coalesce(conceded_home,0)+4*pas)/(coalesce(n_home,0)+4)) hconcede,
   greatest(.05,(((((.25*hgf+.75*hxgf)+12*(.25*lhg+.75*lhx))/(hn+12))*(((.25*aga+.75*axga)+12*(.25*lhg+.75*lhx))/(an+12)))/nullif((.25*lhg+.75*lhx),0)) lbh,
   greatest(.05,(((((.25*agf+.75*axgf)+12*(.25*lag+.75*lax))/(an+12))*(((.25*hga+.75*hxga)+12*(.25*lag+.75*lax))/(hn+12)))/nullif((.25*lag+.75*lax),0)) lba
 from z
), probs as (
 select *,
   100*(1-exp(-(l15h+l15a))*(1+(l15h+l15a))) p15,
   100*(1-exp(-(l25h+l25a))*(1+(l25h+l25a)+power(l25h+l25a,2)/2)) p25,
   100*(1-exp(-(l25h+l25a))*(1+(l25h+l25a)+power(l25h+l25a,2)/2+power(l25h+l25a,3)/6)) p35,
   100*(1-exp(-(l45h+l45a))*(1+(l45h+l45a)+power(l45h+l45a,2)/2+power(l45h+l45a,3)/6+power(l45h+l45a,4)/24)) p45,
   100*(.75*((1-exp(-lbh))*(1-exp(-lba)))+.25*(((hscore+aconcede)/2)*((ascore+hconcede)/2))) pbtts,
   greatest(h_asof,a_asof,lg_asof) asof,
   (p_decision_time<kickoff and hn>=6 and an>=6 and greatest(h_asof,a_asof,lg_asof)<=p_decision_time) temporal_ok
 from calc
), rows as (
 select 'TOTAL_1_5'::text mk,'Over/Under'::text ml,1.5::numeric ln,p15 py,100-p15 pn,'soccer_total15_v1'::text mv,75::numeric threshold from probs
 union all select 'TOTAL_2_5','Over/Under',2.5,p25,100-p25,'soccer_total25_v1_challenger',62.5 from probs
 union all select 'TOTAL_3_5','Over/Under',3.5,p35,100-p35,'soccer_total35_v1_challenger',72.5 from probs
 union all select 'TOTAL_4_5','Over/Under',4.5,p45,100-p45,'soccer_total45_v1_challenger',80 from probs
 union all select 'BTTS','BTTS',null,pbtts,100-pbtts,'soccer_btts_occurrence_v1_challenger',60 from probs
)
select p_event_id,p.endpoint,p.home_nombre,p.away_nombre,p.kickoff,p_decision_time,p.asof,
  r.mk,r.ml,r.ln,round(r.py,2),round(r.pn,2),
  case when r.mk like 'TOTAL_%' then case when r.py>=r.pn then 'Over '||r.ln::text else 'Under '||r.ln::text end
       when r.py>=r.pn then 'BTTS Sí' else 'BTTS No' end,
  round(greatest(r.py,r.pn),2),r.mv,
  case
    when not p.temporal_ok then 'TEMPORAL_BLOCKED'
    when r.mk='TOTAL_1_5' and greatest(r.py,r.pn)>=r.threshold then 'READY'
    when r.mk='TOTAL_1_5' then 'BELOW_PUBLICATION_THRESHOLD'
    else 'CHALLENGER_SHADOW'
  end,
  p.temporal_ok,
  jsonb_build_object('home_n',p.hn,'away_n',p.an,'league_home_g',p.lhg,'league_away_g',p.lag,
    'data_asof',p.asof,'decision_time',p_decision_time,'market_used_in_probability',false,
    'publication_threshold_pct',r.threshold,'model_family','RETO_SECONDARY_SOCCER_V1')
from probs p cross join rows r;
$$;

revoke all on function v2.fn_soccer_secondary_market_v1(text,timestamptz) from public,anon,authenticated;

create or replace function v2.capture_soccer_secondary_markets_v1(p_horizon_hours integer default 240)
returns jsonb language plpgsql security definer set search_path='v2','public','pg_temp' as $$
declare e record; r record; n int:=0; v_now timestamptz:=now();
begin
  for e in
    select a.espn_event_id from public.agenda_espn a
    where a.deporte='soccer' and a.fecha>v_now and a.fecha<=v_now+make_interval(hours=>p_horizon_hours)
      and a.espn_endpoint in ('soccer/eng.1','soccer/esp.1','soccer/ger.1','soccer/fra.1','soccer/ita.1')
  loop
    for r in select * from v2.fn_soccer_secondary_market_v1(e.espn_event_id,v_now) loop
      insert into v2.soccer_secondary_prediction_v1
        (espn_event_id,endpoint,home_team,away_team,kickoff,decision_time,data_asof,market_key,market_label,line,p_yes,p_no,candidate_pick,candidate_pick_prob,model_version,model_status,temporal_safe,feature_snapshot)
      values(r.espn_event_id,r.endpoint,r.home_team,r.away_team,r.kickoff,r.decision_time,r.data_asof,r.market_key,r.market_label,r.line,r.p_yes,r.p_no,r.candidate_pick,r.candidate_pick_prob,r.model_version,r.model_status,r.temporal_safe,r.feature_snapshot)
      on conflict do nothing;
      n:=n+1;
    end loop;
  end loop;
  return jsonb_build_object('captured_rows',n,'decision_time',v_now,'horizon_hours',p_horizon_hours);
end $$;
revoke all on function v2.capture_soccer_secondary_markets_v1(integer) from public,anon,authenticated;

create or replace view public.v_soccer_secondary_market_publication_v1 as
with latest as (
  select distinct on(s.espn_event_id,s.market_key,s.model_version) s.*
  from v2.soccer_secondary_prediction_v1 s
  order by s.espn_event_id,s.market_key,s.model_version,s.decision_time desc
), gated as (
  select l.*,r.scientific_ready,r.publish_authorized as registry_publish,r.money_authorized,r.validation_status,r.release_threshold_pct,
         coalesce(p.publish_authorized,false) policy_publish,
         (r.scientific_ready and r.publish_authorized and coalesce(p.publish_authorized,false) and l.model_status='READY' and l.temporal_safe) official
  from latest l
  join v2.soccer_secondary_model_registry_v1 r using(model_version)
  left join v2.soccer_secondary_market_policy_v1 p on p.endpoint=l.endpoint and p.model_version=l.model_version
)
select espn_event_id,endpoint,home_team,away_team,kickoff,market_key,market_label,line,
  case when official then p_yes end as p_reto_yes,
  case when official then p_no end as p_reto_no,
  case when official then candidate_pick end as canonical_pick,
  case when official then candidate_pick_prob end as canonical_pick_prob,
  model_version,validation_status,
  case when official then 'OFFICIAL' when model_status='BELOW_PUBLICATION_THRESHOLD' then 'NO_PICK_THRESHOLD' else 'CHALLENGER' end as publication_status,
  official as selector_authoritative,false as money_authorized,
  case when official then 'P_RETO secondary market OOS-confirmed; market never selects probability.'
       when model_status='BELOW_PUBLICATION_THRESHOLD' then 'Validated market, but this event is below the publication confidence threshold.'
       else 'Shadow challenger; RETO does not publish a probability/pick yet.' end as publication_reason,
  decision_time,data_asof,feature_snapshot
from gated;

grant select on public.v_soccer_secondary_market_publication_v1 to anon,authenticated;

create or replace function v2.refresh_soccer_secondary_learning_v1()
returns jsonb language plpgsql security definer set search_path='v2','public','pg_temp' as $$
declare n int:=0;
begin
  with s as (
    select distinct on(p.espn_event_id,p.market_key,p.model_version) p.*
    from v2.soccer_secondary_prediction_v1 p
    where p.temporal_safe and p.decision_time<p.kickoff
    order by p.espn_event_id,p.market_key,p.model_version,p.decision_time desc
  ), x as (
    select s.*,m.home_score hs,m.away_score aws,m.status result_status
    from s cross join lateral public.buscar_marcador(s.espn_event_id) m
    where m.home_score is not null and m.away_score is not null
      and lower(coalesce(m.status,'')) in ('post','final','finished','status_final','status_full_time')
  ), ins as (
    insert into v2.model_learning_observation
      (source_system,source_key,espn_event_id,sport,league,market,model_version,eval_window,snapshot_at,kickoff,
       temporal_safe,promotion_eligible,n_classes,p1,p2,outcome_idx,line,score_home,score_away,meta)
    select 'SOCCER_SECONDARY_V1',concat_ws('|','SOC2',espn_event_id,model_version,market_key),espn_event_id,
      'soccer',endpoint,
      case market_key when 'BTTS' then 'BTTS' else 'Over/Under '||line::text end,
      model_version,'pregame_latest',decision_time,kickoff,true,true,2,p_yes/100.0,p_no/100.0,
      case when market_key='BTTS' then case when hs>0 and aws>0 then 1 else 2 end
           else case when (hs+aws)>line then 1 else 2 end end,
      line,hs,aws,jsonb_build_object('market_key',market_key,'model_status',model_status,'feature_snapshot',feature_snapshot)
    from x
    on conflict(source_key) do nothing returning 1
  ) select count(*) into n from ins;
  return jsonb_build_object('new_observations',n,'total_secondary_observations',
    (select count(*) from v2.model_learning_observation where source_system='SOCCER_SECONDARY_V1'));
end $$;
revoke all on function v2.refresh_soccer_secondary_learning_v1() from public,anon,authenticated;

create or replace view public.v_reto_brain_release_authority_v2 as
select * from public.v_reto_brain_release_authority_v1
union all
select 'soccer'::text sport,('endpoint:'||p.endpoint)::text league_scope,
  case r.market_key when 'BTTS' then 'BTTS' else 'Over/Under '||r.line::text end::text market,
  r.model_version,r.scientific_ready,
  (r.publish_authorized and p.publish_authorized) as product_release_authorized,
  r.money_authorized,
  case when r.publish_authorized and p.publish_authorized then 'RELEASE_READY_SELECTIVE' else 'LAB_ONLY' end::text release_status,
  r.validation_status,null::text live_status,null::int live_n,null::int live_market_n,
  null::numeric live_brier_model,null::numeric live_brier_naive,null::numeric live_brier_reference,
  null::numeric live_vs_naive_upper95,null::numeric live_vs_market_upper95,
  null::numeric live_calibration_gap_pp,null::numeric live_accuracy_pct,null::numeric live_avg_confidence_pct,null::numeric market_coverage_pct,
  p.reason::text reason,
  r.validation_evidence||jsonb_build_object('release_threshold_pct',r.release_threshold_pct,'money_authorized',r.money_authorized,'market_role','diagnostic-only') evidence,
  greatest(r.sealed_at,p.updated_at) updated_at
from v2.soccer_secondary_model_registry_v1 r
join v2.soccer_secondary_market_policy_v1 p using(model_version);
grant select on public.v_reto_brain_release_authority_v2 to anon,authenticated;

create or replace view public.v_soccer_secondary_invariant_leaks_v1 as
select espn_event_id,market_key,'OFFICIAL_WITHOUT_EXACT_AUTHORITY'::text leak
from public.v_soccer_secondary_market_publication_v1
where publication_status='OFFICIAL' and selector_authoritative is distinct from true
union all
select espn_event_id,market_key,'OFFICIAL_BAD_PROBABILITY'::text
from public.v_soccer_secondary_market_publication_v1
where publication_status='OFFICIAL' and (p_reto_yes is null or p_reto_no is null or abs((p_reto_yes+p_reto_no)-100)>0.05)
union all
select espn_event_id,market_key,'OFFICIAL_MONEY_LEAK'::text
from public.v_soccer_secondary_market_publication_v1
where publication_status='OFFICIAL' and money_authorized is distinct from false
union all
select espn_event_id,market_key,'TEMPORAL_LEAK'::text
from v2.soccer_secondary_prediction_v1
where temporal_safe is distinct from true or decision_time>=kickoff or (data_asof is not null and data_asof>decision_time);

grant select on public.v_soccer_secondary_invariant_leaks_v1 to authenticated;

create or replace view public.v_reto_brain_health_v2 as
select h.*,
  (select count(*) from public.v_soccer_secondary_invariant_leaks_v1) as secondary_market_invariant_failures,
  (select count(*) from public.v_soccer_secondary_market_publication_v1 where publication_status='OFFICIAL') as secondary_official_rows,
  case when h.status='PASS' and (select count(*) from public.v_soccer_secondary_invariant_leaks_v1)=0 then 'PASS' else 'FAIL' end as status_v2
from public.v_reto_brain_health_v1 h;
grant select on public.v_reto_brain_health_v2 to authenticated;

revoke all on v2.soccer_secondary_model_registry_v1,v2.soccer_secondary_market_policy_v1,v2.soccer_secondary_prediction_v1 from anon,authenticated;

-- Capture and grading jobs. Recreate idempotently.
select cron.unschedule(jobid) from cron.job where jobname='reto-soccer-secondary-capture-v1';
select cron.schedule('reto-soccer-secondary-capture-v1','12,42 * * * *','select v2.capture_soccer_secondary_markets_v1(240);');
select cron.unschedule(jobid) from cron.job where jobname='reto-soccer-secondary-learning-v1';
select cron.schedule('reto-soccer-secondary-learning-v1','57 * * * *','select v2.refresh_soccer_secondary_learning_v1();');
