-- ============================================================================
-- iss029 — APROBACIÓN DE LIGAS DOMÉSTICAS (BLOQUE 2) · STAGED, NO APLICAR
-- ============================================================================
-- Validación OOS del motor Dixon-Coles INTRA-LIGA (sin φ) sobre 5 ligas domésticas
-- no aprobadas. Temporalmente seguro (forma 540d < kickoff). Baseline = base-rate.
-- Evidencia: shadow-patches/reports/BLOQUE2_domesticas_2026-09-09.md
--            lab/domestic_leagues_v1/ (validate_domestic.py, domestic_result.json)
-- Gate de calibración: ECE <= 0.08 además de mejora OOS en Brier y LogLoss.
-- Leakage gate: 0 filas fechadas hoy/live en el fit de las 5 ligas (verificado).
--
-- NO va en supabase/migrations. NO aplicar bajo freeze.
-- ============================================================================

-- ESTADO (tras AUDIT_NO_PASS de ChatGPT, issue #4 comment 5606659045):
-- NINGUNA liga se aprueba todavía. Belgica/Dinamarca/Escocia quedan
-- APPROVABLE_STAGED / FINAL_VALIDATION_PENDING (NO 'approved'). El label 'approved'
-- exige antes: (a) que el código de validación use EXACTAMENTE el algoritmo/
-- feature_version de PRODUCCIÓN (Motor B) que servirá esas ligas — no un
-- Dixon-Coles de laboratorio; (b) walk-forward / rolling folds + bootstrap CI
-- contra un baseline FUERTE del MISMO modelo (no base-rate); (c) calibración fina.
-- Ver BLOQUE2b (iss029b) para la validación endurecida.
--
-- APPROVABLE_STAGED (candidatas, NO insertar approved aún):
--   144 Jupiler (Brier 0.622 vs base 0.660, ECE 0.011) — la más fuerte.
--   119 Danish  (Brier 0.638 vs base 0.656, ECE 0.05).
--   179 Scottish(Brier 0.567 vs base 0.631, ECE 0.06).
-- NOT_APPROVABLE (mal calibradas, ECE>0.08): 103 Noruega (0.12), 197 Grecia (0.097).
-- El INSERT de approval queda intencionalmente FUERA hasta pasar BLOQUE2b.

-- Nota identidad competencia/proveedor: liga_id de ESPN es la clave canónica
-- (v_futpro_v2 y historico_partidos_espn comparten liga_id). No hay ambigüedad
-- de proveedor en estas 5 (todas single-country, un solo liga_id por competencia).
