-- ISS130 SUPERSEDED — DO NOT APPLY.
-- The first staged draft reused v2.fantasy_projection_snapshot, but disposable audit
-- proved that name already belongs to an older incompatible experimental contract.
-- Reusing it would create parallel/ambiguous Fantasy authorities.
--
-- Authoritative replacement: iss130b_fantasy_b1_rq80_authority_v2.sql
-- It uses v2.fantasy_projection_snapshot_v2 and contains the full canonical model,
-- calibration, temporal snapshot and fail-close contract.
